// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCha6lcOZkiTbXz2oqYh2IwAHEDf8LC9A',
    appId: '1:457087090605:web:3c4042ce4db0bc0d77ab24',
    messagingSenderId: '457087090605',
    projectId: 'newecommerce-a16aa',
    authDomain: 'newecommerce-a16aa.firebaseapp.com',
    storageBucket: 'newecommerce-a16aa.appspot.com',
    measurementId: 'G-BDTNJL23W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwwl-Na0PAqBvs_f-5qwC7upzwieQ7Hkc',
    appId: '1:457087090605:android:1b71e794ea654aea77ab24',
    messagingSenderId: '457087090605',
    projectId: 'newecommerce-a16aa',
    storageBucket: 'newecommerce-a16aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBxdAcJOx2zq0BtxQXPBgqeQPfeXho068',
    appId: '1:457087090605:ios:6c602d113b53d43177ab24',
    messagingSenderId: '457087090605',
    projectId: 'newecommerce-a16aa',
    storageBucket: 'newecommerce-a16aa.appspot.com',
    iosBundleId: 'com.example.elixir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBxdAcJOx2zq0BtxQXPBgqeQPfeXho068',
    appId: '1:457087090605:ios:d3af2afc56a760d877ab24',
    messagingSenderId: '457087090605',
    projectId: 'newecommerce-a16aa',
    storageBucket: 'newecommerce-a16aa.appspot.com',
    iosBundleId: 'com.example.elixir.RunnerTests',
  );
}
